events {
    # Handles network connection processing (required by Nginx syntax)
    worker_connections 1024;
}

http {
    # BLOCK 1: The Upstream Cluster
    upstream app {
        # Docker's internal DNS handles the 3 replicas behind this name
        server app:8080; 
    }

    # BLOCK 2: The Server Frontend
    server {
        listen 80; # Listens inside the container

        # Proxy all incoming traffic to the upstream block above
        location / {
            proxy_pass http://app;
            
            # Forward real user headers so Go knows what's happening
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}